version: '3'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql_db_data_container:/var/lib/mysql
      - ./src/main/resources/init.sql:/data/application/init.sql

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - "8080:8080"


volumes:
  mysql_db_data_container: